from savescope.models.schema_models import SaveSchema, DataType, Endianness

class ParserGenerator:
    """
    Phase 4: Python Parser Generator.
    Produces clean, typed, standalone Python code using @dataclass, struct, and pathlib.
    Generates read_save(), write_save(), and validate_save().
    """

    TYPE_TO_PYTHON = {
        DataType.INT8: "int",
        DataType.UINT8: "int",
        DataType.INT16: "int",
        DataType.UINT16: "int",
        DataType.INT32: "int",
        DataType.UINT32: "int",
        DataType.INT64: "int",
        DataType.UINT64: "int",
        DataType.FLOAT32: "float",
        DataType.FLOAT64: "float",
        DataType.STRING: "str",
        DataType.BOOLEAN: "bool",
        DataType.BYTES: "bytes",
    }

    STRUCT_FORMAT = {
        DataType.INT8: "b",
        DataType.UINT8: "B",
        DataType.BOOLEAN: "?",
        DataType.INT16: "h",
        DataType.UINT16: "H",
        DataType.INT32: "i",
        DataType.UINT32: "I",
        DataType.INT64: "q",
        DataType.UINT64: "Q",
        DataType.FLOAT32: "f",
        DataType.FLOAT64: "d",
    }

    @classmethod
    def generate_code(cls, schema: SaveSchema) -> str:
        cls_name = "".join(part.capitalize() for part in schema.name.split())
        if not cls_name:
            cls_name = "SaveData"

        lines = [
            '"""',
            f'Auto-generated Python Save File Parser for: {schema.name}',
            f'Schema Version: {schema.version}',
            'Generated by SaveScope - Reverse Engineering Toolkit',
            '"""',
            'from dataclasses import dataclass',
            'import struct',
            'from pathlib import Path',
            'from typing import Union, Optional, Any',
            '',
            '@dataclass',
            f'class {cls_name}:',
        ]

        for f in schema.fields:
            py_type = cls.TYPE_TO_PYTHON.get(f.data_type, "Any")
            doc = f"  # Offset: 0x{f.offset:04X} ({f.offset}) | {f.description}" if f.description else f"  # Offset: 0x{f.offset:04X} ({f.offset})"
            lines.append(f'    {f.key}: {py_type}{doc}')

        lines.extend([
            '    _raw_data: Optional[bytearray] = None',
            '',
            '    @classmethod',
            f'    def read_save(cls, path_or_bytes: Union[str, Path, bytes]) -> "{cls_name}":',
            '        if isinstance(path_or_bytes, (str, Path)):',
            '            raw = bytearray(Path(path_or_bytes).read_bytes())',
            '        else:',
            '            raw = bytearray(path_or_bytes)',
            '',
        ])

        if schema.expected_size is not None:
            lines.extend([
                f'        if len(raw) != {schema.expected_size}:',
                f'            raise ValueError(f"Save file size mismatch: expected {schema.expected_size}, got {{len(raw)}} bytes")',
            ])

        if schema.magic_bytes:
            magic_hex = schema.magic_bytes.hex()
            lines.extend([
                f'        expected_magic = bytes.fromhex("{magic_hex}")',
                f'        actual_magic = raw[{schema.magic_offset}:{schema.magic_offset + len(schema.magic_bytes)}]',
                f'        if actual_magic != expected_magic:',
                f'            raise ValueError(f"Invalid magic header: {{actual_magic.hex()}} != {{expected_magic.hex()}}")',
            ])

        # Parsing statements
        field_assignments = []
        for f in schema.fields:
            endian = f.endianness.value if f.endianness else schema.endianness.value
            endian_prefix = "<" if endian == "little" else ">"

            if f.data_type == DataType.STRING:
                length = f.length or 16
                lines.append(f'        # Read String: {f.key} (len={length})')
                lines.append(f'        raw_{f.key} = bytes(raw[{f.offset}:{f.offset + length}])')
                lines.append(f'        null_pos = raw_{f.key}.find(b"\\x00")')
                lines.append(f'        val_{f.key} = (raw_{f.key}[:null_pos] if null_pos != -1 else raw_{f.key}).decode("{f.encoding}", errors="replace")')
            elif f.data_type == DataType.BYTES:
                length = f.length or 1
                lines.append(f'        val_{f.key} = bytes(raw[{f.offset}:{f.offset + length}])')
            else:
                fmt_char = cls.STRUCT_FORMAT.get(f.data_type, "I")
                full_fmt = f'"{endian_prefix}{fmt_char}"'
                lines.append(f'        val_{f.key} = struct.unpack_from({full_fmt}, raw, {f.offset})[0]')
            field_assignments.append(f'{f.key}=val_{f.key}')

        args_str = ", ".join(field_assignments)
        lines.extend([
            '',
            f'        instance = cls({args_str})',
            '        instance._raw_data = raw',
            '        return instance',
            '',
            '    def write_save(self, path: Union[str, Path]) -> None:',
            '        """Writes all modified fields into the raw buffer, preserving untouched bytes."""',
            '        if self._raw_data is None:',
            f'            self._raw_data = bytearray({schema.expected_size or 1024})',
            '',
            '        buf = self._raw_data',
        ])

        for f in schema.fields:
            endian = f.endianness.value if f.endianness else schema.endianness.value
            endian_prefix = "<" if endian == "little" else ">"

            if f.data_type == DataType.STRING:
                length = f.length or 16
                lines.append(f'        # Write String {f.key}')
                lines.append(f'        encoded = self.{f.key}.encode("{f.encoding}", errors="replace")[:{length}]')
                lines.append(f'        buf[{f.offset}:{f.offset + length}] = encoded.ljust({length}, b"\\x00")')
            elif f.data_type == DataType.BYTES:
                lines.append(f'        buf[{f.offset}:{f.offset} + len(self.{f.key})] = self.{f.key}')
            else:
                fmt_char = cls.STRUCT_FORMAT.get(f.data_type, "I")
                full_fmt = f'"{endian_prefix}{fmt_char}"'
                lines.append(f'        struct.pack_into({full_fmt}, buf, {f.offset}, self.{f.key})')

        lines.extend([
            '',
            '        Path(path).write_bytes(buf)',
            '',
            '    def validate(self) -> list[str]:',
            '        """Validates current values against range constraints."""',
            '        errors = []',
        ])

        for f in schema.fields:
            if f.min_value is not None:
                lines.append(f'        if self.{f.key} < {f.min_value}:')
                lines.append(f'            errors.append(f"{f.key} below minimum ({f.min_value}): {{self.{f.key}}}")')
            if f.max_value is not None:
                lines.append(f'        if self.{f.key} > {f.max_value}:')
                lines.append(f'            errors.append(f"{f.key} exceeds maximum ({f.max_value}): {{self.{f.key}}}")')

        lines.extend([
            '        return errors',
            '',
        ])

        return "\n".join(lines)
