"""
Auto-generated Python Save File Parser for: Chronicles of Aeloria
Schema Version: 1.0
Generated by SaveScope - Reverse Engineering Toolkit
"""
from dataclasses import dataclass
import struct
from pathlib import Path
from typing import Union, Optional, Any

@dataclass
class ChroniclesOfAeloria:
    gold: int  # Offset: 0x0010 (16) | Total gold coins held by party
    level: int  # Offset: 0x0014 (20) | Hero experience level
    hp: int  # Offset: 0x0016 (22) | Current hit points
    max_hp: int  # Offset: 0x0018 (24) | Maximum hit points
    hero_name: str  # Offset: 0x0020 (32) | Hero display name
    playtime_seconds: float  # Offset: 0x0030 (48) | Total elapsed playtime in seconds
    _raw_data: Optional[bytearray] = None

    @classmethod
    def read_save(cls, path_or_bytes: Union[str, Path, bytes]) -> "ChroniclesOfAeloria":
        if isinstance(path_or_bytes, (str, Path)):
            raw = bytearray(Path(path_or_bytes).read_bytes())
        else:
            raw = bytearray(path_or_bytes)

        if len(raw) != 256:
            raise ValueError(f"Save file size mismatch: expected 256, got {len(raw)} bytes")
        expected_magic = bytes.fromhex("53534350")
        actual_magic = raw[0:4]
        if actual_magic != expected_magic:
            raise ValueError(f"Invalid magic header: {actual_magic.hex()} != {expected_magic.hex()}")
        val_gold = struct.unpack_from("<I", raw, 16)[0]
        val_level = struct.unpack_from("<B", raw, 20)[0]
        val_hp = struct.unpack_from("<H", raw, 22)[0]
        val_max_hp = struct.unpack_from("<H", raw, 24)[0]
        # Read String: hero_name (len=16)
        raw_hero_name = bytes(raw[32:48])
        null_pos = raw_hero_name.find(b"\x00")
        val_hero_name = (raw_hero_name[:null_pos] if null_pos != -1 else raw_hero_name).decode("ascii", errors="replace")
        val_playtime_seconds = struct.unpack_from("<f", raw, 48)[0]

        instance = cls(gold=val_gold, level=val_level, hp=val_hp, max_hp=val_max_hp, hero_name=val_hero_name, playtime_seconds=val_playtime_seconds)
        instance._raw_data = raw
        return instance

    def write_save(self, path: Union[str, Path]) -> None:
        """Writes all modified fields into the raw buffer, preserving untouched bytes."""
        if self._raw_data is None:
            self._raw_data = bytearray(256)

        buf = self._raw_data
        struct.pack_into("<I", buf, 16, self.gold)
        struct.pack_into("<B", buf, 20, self.level)
        struct.pack_into("<H", buf, 22, self.hp)
        struct.pack_into("<H", buf, 24, self.max_hp)
        # Write String hero_name
        encoded = self.hero_name.encode("ascii", errors="replace")[:16]
        buf[32:48] = encoded.ljust(16, b"\x00")
        struct.pack_into("<f", buf, 48, self.playtime_seconds)

        Path(path).write_bytes(buf)

    def validate(self) -> list[str]:
        """Validates current values against range constraints."""
        errors = []
        if self.gold < 0:
            errors.append(f"gold below minimum (0): {self.gold}")
        if self.gold > 999999:
            errors.append(f"gold exceeds maximum (999999): {self.gold}")
        if self.level < 1:
            errors.append(f"level below minimum (1): {self.level}")
        if self.level > 99:
            errors.append(f"level exceeds maximum (99): {self.level}")
        if self.hp < 0:
            errors.append(f"hp below minimum (0): {self.hp}")
        if self.hp > 9999:
            errors.append(f"hp exceeds maximum (9999): {self.hp}")
        if self.max_hp < 1:
            errors.append(f"max_hp below minimum (1): {self.max_hp}")
        if self.max_hp > 9999:
            errors.append(f"max_hp exceeds maximum (9999): {self.max_hp}")
        if self.playtime_seconds < 0.0:
            errors.append(f"playtime_seconds below minimum (0.0): {self.playtime_seconds}")
        if self.playtime_seconds > 3600000.0:
            errors.append(f"playtime_seconds exceeds maximum (3600000.0): {self.playtime_seconds}")
        return errors
